Single node support
canonical/microcloud pull request #319
Opened 2024-06-12 01:01 UTC by masnax

Adds basic single-node support. This is rebased off of #260 so it's only the last ~13 commits that are relevant. This will probably get broken down into 2 or 3 PRs because there were some reorganization of the network and storage questions.

This adds an initial question to `microcloud init` asking if the user wants to set up just one node.
```
Do you want to concurrently set up more than one cluster member? (yes/no) [default=yes]: 
```

If the user enters `no`, the system will follow the ordinary setup with ZFS and OVN (or optionally a FAN network instead), but the user will not be prompted for a lookup subnet and will not be presented a list of systems.

MicroCeph will be skipped as we require 3 systems. MicroCeph does not yet support a way to modify OSD configuration from the API, so we cannot change replication rules just yet.

The cluster can be grown after this point by using `microcloud add`.

A few changes were made to the disk and network selection to inspect LXD's storage pools and networks to determine if the existing local node should be included in the list for disk selection. 

TODO:

- [ ] Add tests
- [ ] Support preseed
- [ ] Support adding missing services (maybe, if it makes sense)
- [ ] Test MicroOVN functions properly with 1 node.

2024-07-23 18:42 UTC, masnax commented
Right now, this assumes the current behaviour where MicroCeph requires 3 nodes. This can be configured, but will require changing a lot of the tests which check for MicroCeph to be skipped with fewer than 3 nodes.

Preseed is also ignored here. We arbitrarily require at least 2 nodes for preseed but this doesn't necessarily have to be the case anymore.

2024-08-28 09:14 UTC, roosterfish requested changes
Looks good, only two small comments.

What is missing when it comes to adding existing services? Do you think about something like deploying a single node MicroCloud without OVN and then adding OVN to it later using `service add`?

Should the option of single node MicroCloud also be reflected in the docs? I was thinking about something like https://canonical-microcloud.readthedocs-hosted.com/en/latest/microovn/tutorial/single-node/.

The PRs description still says Ceph will be skipped but after https://github.com/canonical/microcloud/pull/378 got merged I think this sentence can be removed too.

2024-08-28 14:56 UTC, masnax commented on cmd/microcloud/main_init_preseed.go
> +				if k < currentIface || currentIface == "" {
It's a loop that assigns the first alphabetical interface to `ifaceByPeer` if it lacks a value for that key. So we need to check for two cases: 
* `ifaceByPeer` lacks a value for that key, so we should assign one
* `ifaceByPeer` doesn't lack a value, but its value is alphabetically later than the new value.

2024-08-28 15:54 UTC, roosterfish commented on cmd/microcloud/main_init_preseed.go
> +				if k < currentIface || currentIface == "" {
I see, thanks for clarification. 
And since it's a map we cannot just pick the first entry as the results aren't guaranteed to be ordered.

2024-08-28 15:59 UTC, roosterfish commented
As mentioned earlier the only other thing I found with this PR is adding services (like MicroOVN) after the single node MicroCloud is deployed seems to be not working currently.

It reports `Error: All services have already been set up`:

```
root@m1:~# microcloud init
Waiting for LXD to start ...
Do you want to set up more than one cluster member? (yes/no) [default=yes]: no
Select an address for MicroCloud's internal traffic:

 Using address "10.165.133.71" for MicroCloud

Gathering system information ...
Would you like to set up local storage? (yes/no) [default=yes]:  
Select exactly one disk from each cluster member:

Select which disks to wipe:

 Using "/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_lxd_volm1--local" on "m1" for local storage pool

Would you like to set up distributed storage? (yes/no) [default=yes]: 
Select from the available unpartitioned disks:

Select which disks to wipe:

Disk configuration does not meet recommendations for fault tolerance. At least 3 systems must supply disks.
Continuing with this configuration will leave MicroCloud susceptible to data loss
Change disk selection? (yes/no) [default=yes]: no
 Using 1 disk(s) on "m1" for remote storage pool

Do you want to encrypt the selected disks? (yes/no) [default=no]: 
Would you like to set up CephFS remote storage? (yes/no) [default=yes]: 
What subnet (either IPv4 or IPv6 CIDR notation) would you like your Ceph internal traffic on? [default: 10.165.133.0/24] 
Configure distributed networking? (yes/no) [default=yes]: no
Initializing new services
 Local MicroCloud is ready
 Local LXD is ready
 Local MicroOVN is ready
 Local MicroCeph is ready
Awaiting cluster formation ...
Configuring cluster-wide devices ...
MicroCloud is ready
root@m1:~# microcloud service add
Error: All services have already been set up
```

2024-08-28 18:28 UTC, masnax commented
@roosterfish Ah I see, it's just a miscommunication. `microcloud service add` does not let you re-configure services that are already clustered, it _initializes_ new services that were not previously initialized.

For example, if MicroOVN was not installed when `microcloud init` was first run, but installed later. You can then use `microcloud service add` to add MicroOVN to the MicroCloud cluster.

You get the error `Error: All services have already been set up` because MicroOVN has already been initialized by MicroCloud during `microcloud init`, the configuration on the LXD side is what was skipped.

2024-08-29 07:37 UTC, roosterfish commented
> You get the error `Error: All services have already been set up` because MicroOVN has already been initialized by MicroCloud during `microcloud init`, the configuration on the LXD side is what was skipped.

Thanks I see but is it a bug that MicroCloud initializes MicroOVN as you can see in the output above I have proactively answered `no` on the `Configure distributed networking?` question?

2024-08-29 14:09 UTC, masnax commented
> > You get the error `Error: All services have already been set up` because MicroOVN has already been initialized by MicroCloud during `microcloud init`, the configuration on the LXD side is what was skipped.
> 
> Thanks I see but is it a bug that MicroCloud initializes MicroOVN as you can see in the output above I have proactively answered `no` on the `Configure distributed networking?` question?
> 
> It gave me a single node MicroCloud using fan networking so I would suspect MicroCloud doesn't even look at MicroOVN in this situation.

Configure != Initialize. MicroCloud will form the MicroOVN cluster if the snap is installed irrespective of whether or not you want to configure the network in LXD at the precise moment you ran `microcloud init`. The primary objective is to create the clusters. If a user wants to configure their network some other way, then at least they will have the MicroOVN cluster formed.

2024-08-29 14:54 UTC, masnax commented on cmd/microcloud/main_init.go
> +	// setupMany indicates whether we are setting up remote nodes concurrently, or just the a single cluster member.
Fixed

2024-08-29 14:59 UTC, roosterfish approved these changes
LGTM!

2024-08-29 18:01 UTC, merged

2024-08-30 12:09 UTC, token47 commented
Sunbeam uses very similar approach and can do microceph in one node. Can't the same be done for microcloud?

2024-08-30 14:28 UTC, masnax commented
> Sunbeam uses very similar approach and can do microceph in one node. Can't the same be done for microcloud?

If you're referring to the line in the PR description about MicroCeph being skipped, that was out of date and is now removed. Single node does support MicroCeph.