Include 'lookup_interface' in preseed example and Use the correct ovn interface
canonical/microcloud pull request #328
Opened 2024-06-22 21:06 UTC by WizardBit

The preseed yaml file used as an example in the [docs](https://canonical-microcloud.readthedocs-hosted.com/en/latest/how-to/initialise/#howto-initialise-preseed) does not include the option 'lookup_subnet'. 

As this preseed example closely aligns with the [get started guide](https://canonical-microcloud.readthedocs-hosted.com/en/latest/tutorial/get_started/) `eth1` was changed  to `enp6s0` to avoid confusion with the device name added to the VM.

Not included in this PR, as I cannot find additional information on the behavior, is  `reuse_existing_clusters` which is also missing.

2024-06-24 08:03 UTC, roosterfish requested changes

2024-06-24 08:03 UTC, roosterfish commented on doc/how-to/preseed.yaml
> +lookup_interface: enp5s0
Thanks for this! It should be `eth0`. Please see the other comment.

2024-06-24 08:08 UTC, roosterfish commented
@WizardBit thanks for your contribution. 

Your mail `82845986+WizardBit@users.noreply.github.com` is failing the CLA check. Could you please use another one? 

In the commit messages we put a prefix which makes it easier to identify the change in the long list of commits. See https://github.com/canonical/microcloud/commit/48695e6 as an example.

2024-06-24 22:04 UTC, WizardBit commented
@roosterfish Thank you for the clarification and glad to help add this missing option.

2024-06-25 07:05 UTC, roosterfish commented
Thanks for changing the mail, just one more thing. Can you please squash the two commits together? It is so that you don't add stuff and delete it in the next commit again.

2024-06-26 07:44 UTC, roosterfish approved these changes
LGTM!

2024-06-26 07:47 UTC, roosterfish commented
> LGTM!

@WizardBit it looks that GitHub doesn't recognize the signing key that you have used. Have you added the key also to https://github.com/settings/keys under "Signing keys"?

2024-06-27 08:12 UTC, merged