cmd/microcloudd: Set minimum heartbeat value
canonical/microcloud pull request #414
Opened 2024-10-08 19:35 UTC by MggMuggins

Follow-up from #407 

200ms is somewhat arbitrary; we want to explicitly disallow 0 but still let fairly small values through for future use in the test suite.

2024-10-08 21:36 UTC, masnax requested changes

2024-10-08 21:36 UTC, masnax commented on cmd/microcloudd/main.go
> +const MinimumHeartbeatInterval = time.Millisecond * 200
Exported declarations should have a comment. (static analysis should have caught this, guess it's incomplete in microcloud).

2024-10-09 07:49 UTC, roosterfish requested changes
Thanks for the follow up, only a small nit.

2024-10-09 07:49 UTC, roosterfish commented on cmd/microcloudd/main.go
> +		return fmt.Errorf("Invalid heartbeat interval: must be >%s", MinimumHeartbeatInterval)
```suggestion
		return fmt.Errorf("Invalid heartbeat interval: Must be >%s", MinimumHeartbeatInterval)
```

2024-10-11 09:43 UTC, roosterfish approved these changes

2024-10-11 09:43 UTC, roosterfish commented
Is 200ms a strict limitation or did you see values less than 200ms cause trouble elsewhere?

2024-10-11 14:45 UTC, MggMuggins commented
It's entirely arbitrary, I just needed a duration >0. It's used as the [dqlite cluster role adjustment frequency](https://pkg.go.dev/github.com/canonical/go-dqlite@v1.22.0/app#WithRolesAdjustmentFrequency) and the MicroCluster heartbeat interval, both of which used to default to 30s. If this were MicroCluster I'd be a little more cautious about the value. You're likely right that there would be issues turning it below 200ms, but I have no evidence for that.

2024-10-11 16:00 UTC, masnax approved these changes

2024-10-11 16:00 UTC, merged