Report if skipping local storage & ovn config
canonical/microcloud pull request #431
Opened 2024-10-17 05:07 UTC by masnax

Prints a message rather than a log when skipping local storage. I thought to avoid a question in this case because the immediate question is for remote storage, and a user may not have enough disks for both.

For OVN config, we do ask a question because FAN networks are being phased out and is not an ideal alternative to MicroOVN anyway. Now, if any systems are ineligible, we immediately ask if the user wants to abort setup. If they choose to continue, we fallback to a FAN network.

2024-10-17 08:46 UTC, roosterfish requested changes
Looking good, only one small remark to have consistent error messages.

2024-10-17 08:46 UTC, roosterfish commented on cmd/microcloud/ask.go
> +		fmt.Println("Skipping local storage pool setup, some systems do not have an available disk")
Let's be consistent and use the same scheme as the error for distributed storage which is `No disks available for distributed storage. Skipping configuration` and use this instead:
```suggestion
		fmt.Println("No disks available for local storage. Skipping configuration")
```

2024-10-17 14:54 UTC, roosterfish submitted a review, later dismissed

2024-10-17 15:36 UTC, gabrielmougard submitted a review, later dismissed
Very good :+1:

2024-10-21 07:53 UTC, roosterfish commented
Looks like this requires some alignments to the interactive vars. Two suites fail on `Some systems are ineligible for distributed networking, which requires either an interface with no IPs assigned or a bridge. Continue anyway?`

2024-10-22 08:33 UTC, roosterfish approved these changes
Looks good!

2024-10-22 08:33 UTC, merged