doc/preseed: doc fixes in preseed file
canonical/microcloud pull request #462
Opened 2024-11-05 10:42 UTC by gabrielmougard

JIRA ticket: https://warthogs.atlassian.net/browse/LXD-2124

* Add missing field in preseed YAML file.
* Add more explanations on what resources the Ceph networks are conveying.

2024-11-05 14:13 UTC, minaelee requested changes
Updating `preseed.yaml` in a way that adds/removes lines requires that the two files that reference it, `add_machine.md` and `initialise.md`, are updated so that each file's `emphasize-lines` list contains the commented lines. Can you add those files to this commit? 

The updated list in both files should be:
```
:emphasize-lines: 1-3,6-8,11-12,15-17,20,23-25,28-33,61-64,70,77-85
```

2024-11-05 14:52 UTC, gabrielmougard commented
> Updating `preseed.yaml` in a way that adds/removes lines requires that the two files that reference it, `add_machine.md` and `initialise.md`, are updated so that each file's `emphasize-lines` list contains the commented lines. Can you add those files to this commit?
> 
> The updated list in both files should be:
> 
> ```
> :emphasize-lines: 1-3,6-8,11-12,15-17,20,23-25,28-33,61-64,70,77-85
> ```

thanks, I'll do that.

2024-11-06 08:58 UTC, minaelee approved these changes
lgtm!

2024-11-06 14:22 UTC, roosterfish approved these changes

2024-11-06 14:23 UTC, merged