Misc test tweaks
canonical/microcloud pull request #542
Opened 2024-12-10 22:34 UTC by simondeziel

2024-12-13 16:01 UTC, roosterfish requested changes
Thanks, only a few comments.

2024-12-13 16:05 UTC, simondeziel commented on cmd/microcloud/ask.go
> +		passwordSplit := strings.SplitN(password, " ", 5)
I went with splitting for "1 more than we expect" specifically to catch badly formatted input. Splitting for the exact number of part means we could get `["foo", "bar", "bar", "oof "]` (note the trailing space after `oof`).

2024-12-13 16:07 UTC, simondeziel commented on service/session.go
> +		if len(splitLine) != 2 {
Same rational regarding splitting for one too many.

And, yeah, the compiler probably optimized that `splitLineLength` var away but I just learned about the metadata surrounding `strings` in Golang ;)

2024-12-13 16:08 UTC, simondeziel commented on test/suites/instances.sh
> +    packages:
The cloud-init recipe includes one last step of `curl`'ing the `Ready` string to `devlxd` which is one of the few status updates the instance can do itself.

2024-12-13 16:11 UTC, simondeziel commented on cmd/microcloud/ask.go
> +		passwordSplit := strings.SplitN(password, " ", 5)
@masnax would it be in that function that left/right trimming should happen so you can lazily copy-n-paste a full line of something like that:

```
Here's the generated passphrase generated for you that you need to input in all other nodes:

   foo bar baz off

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

2024-12-13 17:00 UTC, roosterfish commented on cmd/microcloud/ask.go
> +		passwordSplit := strings.SplitN(password, " ", 5)
Mhh I see then I propose the following to trim and split properly: Have another anonymous func that properly trims and splits as this is only the validator but the actual password returned from `AskString` also needs to be trimmed and cut:

```go
format := func(password string) error {
    trimmed := strings.Trim(password)
    passwordSplit := strings.SplitN(password, " ", 4)

    // Now we can be sure that splitting into 4 sub strings would also work with something like "     a b c d   " as we have trimmed the string beforehand.
    if len(passwordSplit) != 4 {
        return fmt.Errorf("Passphrase has to contain exactly four elements")
    }
}
```

2024-12-13 17:01 UTC, roosterfish commented on cmd/microcloud/ask.go
> +		passwordSplit := strings.SplitN(password, " ", 5)
And the `format(string)` can then be used both within the `validator()` and later on `password` returned from `AskString`.

2024-12-13 22:11 UTC, simondeziel commented on cmd/microcloud/ask.go
> +		passwordSplit := strings.SplitN(password, " ", 5)
I think we really need to split for "one too many" so that we can reject `a b c d e` while still accepting `a b c d`.

2024-12-16 08:19 UTC, roosterfish commented on cmd/microcloud/ask.go
> +		passwordSplit := strings.SplitN(password, " ", 5)
You are right, otherwise the error will only be returned in case the password is shorter than 4 words.

2024-12-16 08:21 UTC, roosterfish approved these changes

2024-12-16 08:21 UTC, merged